# Welcome to YAKA Games Jekyll Theme !
# Version : 1.0.0
#
# This is a bootsrap 5 theme for Jekyll engine
# This config file is meant for settings that affect your whole site
# Others settings are in /_settings/

#
# Site Information
#
title: Symphony
description: "We are a young indie game studio developing multiplatform IA empowered games and augmented reality experiences."
timezone: UTC
url: "https://yakagamestudio.github.io"
permalink: /news/:categories/:year/:month/:day/:title
tagline: Game developer unleashed 
logo: "/assets/logo.png"
favicon: "assets/icons/favicon.ico"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

#
# Author Information
#
authors:
  default:
    name: YAKA Game Studio
    email: contact@yaka.games
    site: https://yaka.games
  author-1:
    name: Author 1
    position: An editor at Blogzine
    email: contact@yaka.games
    avatar: "/assets/images/avatar1.jpg"
    biography: "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
    social:
      twitter:
        username: koubyak
        link: https://twitter.com/yakagamestudio
      github:
        name: GitHub
        username: koubyak
        link: https://facebook.com/yakagamestudio
      instagram:
        name: Instagram
        username: yakagamestudio
        link: https://instagram.com/yakagamestudio
      linkedin:
        name: LinkedIn
        link: https://www.linkedin.com/showcase/yakagamestudio
      website: https://yaka.games

#
# Defaults values
#
defaults:
# all posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      image: post.jpeg
      author: author-1
  # all pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      image: page.jpeg

#
# Files excluded
#
exclude:
  - readme.md

#
# Plugins used
#
plugins:
  - jekyll-github-metadata
  - jekyll-feed             #https://github.com/jekyll/jekyll-feed
  - jekyll-archives         #https://github.com/jekyll/jekyll-archives
  - jekyll-sitemap          #https://github.com/jekyll/jekyll-sitemap
  - jekyll-avatar           #https://github.com/jekyll/jekyll-avatar
  - jekyll-seo-tag          #https://github.com/jekyll/jekyll-seo-tag
  - jekyll-mentions         #https://github.com/jekyll/jekyll-mentions
  - jekyll-redirect-from    #https://github.com/jekyll/jekyll-redirect-from
#
# Plugins settings
#
paginate: 10

# Archives
jekyll-archives:
  enabled:
    - tags
    - categories
  layout: default
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

#
# Site Settings
#
settings:
  # Languages
  language: fr
  locale: en_US
  # Theme
  theme:
    color:
      primary: "#6f42c1"
      secondary: "#000000"
      background: "#000000"
    font: 
  # Search Engine
  webmaster:
    google: 
    bing: 
    alexa: 
    yandex: 
    baidu: 
    facebook: 
  analytics: "UA-171033127-2"
  # Navigation Menu
  menus:
  - title: Home Menu
    location: header
    position: left
    links:
    - title: Home
      link: "/"
    - title: News
      link: "/news/"
  - title: Network
    location: header
    links:
    - title: Studio
      link: https://yaka.studio
    - title: Play
      link: https://yaka.studio
      icon: 
  - title: Footer Menu 1
    location: footer
    links:
    - title: Link 1
      link: "/news/"
    - title: Link 2
      link: "/news/"
    - title: Link 3
      link: https://yaka.studio
  - title: Footer Menu 2
    location: footer
    links:
    - title: Link 1
      link: "/news/"
    - title: Link 2
      link: "/news/"
    - title: Link 3
      link: https://yaka.studio
  # Social Networks
  social:
    twitter:
      name: Twitter
      username: yakagamestudio
      link: https://twitter.com/yakagamestudio
      image: image-twitter.png
      card: summary
    facebook:
      name: Facebook
      username: yakagamestudio
      link: https://facebook.com/yakagamestudio
    instagram:
      name: Instagram
      username: yakagamestudio
      link: https://instagram.com/yakagamestudio
    linkedin:
      name: LinkedIn
      link: https://www.linkedin.com/showcase/yakagamestudio
    pinterest:
      username: YAKAGameStudio
      link: https://www.pinterest.fr/
    twitch:
      username: yakagamestudio
      link: https://www.twitch.tv/
    youtube:
      link: https://www.youtube.com/channel/UCqhzZEPsQ18xUt0vc1pekCw
  # Promote
  share:
    twitter: https://twitter.com/share?url=
    facebook: https://www.facebook.com/sharer/sharer.php?u=
    linkedin: https://www.linkedin.com/shareArticle?url=