# Welcome to YAKA Games Jekyll Theme !
# Version : 1.0.0
#
# This is a bootstrap 5 theme for Jekyll engine
# This config file is meant for settings that affect your whole site
# Others settings are in /_settings/

#
# Site Information
#
title: Symphony
description: "This is a bootstrap 5 theme for Jekyll engine"
timezone: UTC
url: "https://yakagamestudio.github.io"
baseurl: "Symphony"
permalink: /news/:categories/:year/:month/:day/:title
tagline: A bootstrap 5 theme for Jekyll 
logo: "/assets/logo.png"
favicon: "assets/icons/favicon.ico"
language: fr
locale: en_US

#
# Defaults values
#
defaults:
# all posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      image: /assets/images/post.jpeg
      author: author-1
  # all pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      image: /assets/images/page.jpeg

#
# Files excluded
#
exclude:
  - readme.md

#
# Plugins used
#
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-feed             #https://github.com/jekyll/jekyll-feed
  - jekyll-mentions         #https://github.com/jekyll/jekyll-mentions
  - jekyll-redirect-from    #https://github.com/jekyll/jekyll-redirect-from