# Welcome to YAKA Games Jekyll Theme !
# Version : 1.0.0
#
# This is a bootsrap 5 theme for Jekyll engine
# This config file is meant for settings that affect your whole site
# Others settings are in /_settings/

#
# Site Information
#
title: Symphony
description: "We are a young indie game studio developing multiplatform IA empowered games and augmented reality experiences."
timezone: UTC
url: "https://yakagamestudio.github.io"
permalink: /news/:categories/:year/:month/:day/:title
tagline: Game developer unleashed 
logo: "/assets/logo.png"
favicon: "assets/icons/favicon.ico"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

#
# Defaults values
#
defaults:
# all posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      image: post.jpeg
      author: author-1
  # all pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      image: page.jpeg

#
# Files excluded
#
exclude:
  - readme.md

#
# Site Settings
#
settings:
  # Languages
  language: fr
  locale: en_US

#
# Plugins used
#
plugins:
  - jekyll-github-metadata
  - jekyll-feed             #https://github.com/jekyll/jekyll-feed
  - jekyll-sitemap          #https://github.com/jekyll/jekyll-sitemap
  - jekyll-avatar           #https://github.com/jekyll/jekyll-avatar
  - jekyll-seo-tag          #https://github.com/jekyll/jekyll-seo-tag
  - jekyll-mentions         #https://github.com/jekyll/jekyll-mentions
  - jekyll-redirect-from    #https://github.com/jekyll/jekyll-redirect-from