# Welcome to Symphony!
#
# Is is a bootsrap theme for Jekyll engine
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# Others settings are in /_settings/

#
# Site Information
#
title: Symphony
url: "https://yakagamestudio.github.io"
permalink: /news/:categories/:year/:month/:day/:title
tagline: Game developer unleashed 
logo: /assets/images/logo.png
description: > 
  We are a young indie game studio developing multiplatform IA empowered games and augmented reality experiences.

# Author settings
author:
  name: YAKA Game Studio
  email: contact@yaka.games
  website: https://yaka.games

# Site Settings
settings:
  language: "en-us"
  resources:
    images: /assets/images/illustrations/
    videos: /assets/videos/
  theme:
    color: 
      primary: "#6f42c1"
      secondary: "#000000"
    font:

# Theme Settings


twitter:
  username: yakagamestudio
  card: summary

facebook:
  app_id:
  publisher: https://facebook.com/yakagamestudio
  admins: 


# Social Network
social:
  twitter:
    username: yakagamestudio
    image: image-twitter.png
    card: summary
    link: https://twitter.com/yakagamestudio
    share: https://twitter.com/share?url=
  facebook:
    link: https://facebook.com/yakagamestudio
    share: https://www.facebook.com/sharer/sharer.php?u=
  instagram:
    link: https://instagram.com/yakagamestudio
  linkedin:
    link: https://www.linkedin.com/showcase/yakagamestudio
    share: https://www.linkedin.com/shareArticle?url=
  pinterest:
    link: https://www.pinterest.fr/YAKAGameStudio
  twitch:
    link: https://www.twitch.tv/yakagamestudio
  youtube:
    link: https://www.youtube.com/channel/UCqhzZEPsQ18xUt0vc1pekCw

collections:
  authors:
  games:
    permalink: /:collection/:name
    output: true

# Default layout
defaults:
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: illustrations/launch.jpeg
      author: llefevre
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Files excluded
exclude:
  - readme.md

# Build settings
# markdown: kramdown

# Jekyl plugins