# Welcome to Symphony!
#
# Is is a bootsrap theme for Jekyll engine
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# Others settings are in /_settings/

#
# Site Information
#
title: Symphony
url: "https://yakagamestudio.github.io"
permalink: /news/:categories/:year/:month/:day/:title
tagline: Game developer unleashed 
logo: /assets/logo.png
description: > 
  We are a young indie game studio developing multiplatform IA empowered games and augmented reality experiences.

# Author settings
author:
  name: YAKA Game Studio
  email: contact@yaka.games
  website: https://yaka.games

# Site Settings
settings:
  language: "en"
  locale: "en_US"
  resources:
    images: /assets/images/
    videos: /assets/videos/
  theme:
    color: 
      primary: "#6f42c1"
      secondary: "#000000"
    font:
  webmaster:
    google:
    bing:
    alexa:
    yandex:
    baidu:
    facebook:


# Navigation
menus:
  - title: Home Menu
    location: header
    position: left
    links:
    - name: Home
      link: /
    - name: News
      link: /news/
  - title: Network
    location: header
    links:
    - name: Studio
      link: https://yaka.studio
    - name: Play
      link: https://yaka.studio
      icon: 
  - title: Footer Menu 1
    location: footer
    links:
    - name: Link 1
      link: /news/
    - name: Link 2
      link: /news/
    - name: Link 3
      link: https://yaka.studio
  - title: Footer Menu 2
    location: footer
    links:
    - name: Link 1
      link: /news/
    - name: Link 2
      link: /news/
    - name: Link 3
      link: https://yaka.studio


# Social Network
social:
  - name: Twitter
    link: https://twitter.com/yakagamestudio
    share: https://twitter.com/share?url=
    username: yakagamestudio
    image: image-twitter.png
    card: summary
  - name: Facebook
    link: https://facebook.com/yakagamestudio
    share: https://www.facebook.com/sharer/sharer.php?u=
  - name: Instagram
    link: https://instagram.com/yakagamestudio
  - name: LinkedIn
    link: https://www.linkedin.com/showcase/yakagamestudio
    share: https://www.linkedin.com/shareArticle?url=
  - name: Pinterest
    link: https://www.pinterest.fr/YAKAGameStudio
  - name: Twitch
    link: https://www.twitch.tv/yakagamestudio
  - name: Youtube
    link: https://www.youtube.com/channel/UCqhzZEPsQ18xUt0vc1pekCw

collections:
  authors:
  games:
    permalink: /:collection/:name
    output: true

# Default layout
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: launch.jpeg
      author: llefevre
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Files excluded
exclude:
  - readme.md

# Build settings
# markdown: kramdown

# Jekyl plugins