# Welcome to Symphony!
#
# Is is a bootsrap theme for Jekyll engine
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Site settings
title: YAKA Studio
url: "https://yakagamestudio.github.io"
permalink: /news/:categories/:year/:month/:day/:title
tagline: Game developer unleashed 
logo: /assets/images/logo.png
theme: 
  primary: "#6f42c1"
  secondary: "#000000"
description: > 
  We are a young indie game studio developing multiplatform IA empowered games and augmented reality experiences.

# Author settings
author:
  name: YAKA Game Studio
  email: contact@yaka.games
  website: https://yaka.games

language: "en-us"

twitter:
  username: yakagamestudio
  card: summary

facebook:
  app_id:
  publisher: https://facebook.com/yakagamestudio
  admins: 


# Social Network
social:
- name: Twitter
  link: https://twitter.com/yakagamestudio
  share: https://twitter.com/share?url=
- name: Facebook
  link: https://facebook.com/yakagamestudio
  share: https://www.facebook.com/sharer/sharer.php?u=
- name: Instagram
  link: https://instagram.com/yakagamestudio
- name: LinkedIn
  link: https://www.linkedin.com/showcase/yakagamestudio
  share: https://www.linkedin.com/shareArticle?url=
- name: Pinterest
  link: https://www.pinterest.fr/YAKAGameStudio
- name: Twitch
  link: https://www.twitch.tv/yakagamestudio
- name: Youtube
  link: https://www.youtube.com/channel/UCqhzZEPsQ18xUt0vc1pekCw

collections:
  authors:
  games:
    permalink: /:collection/:name
    output: true

# Default layout
defaults:
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: /assets/images/illustrations/launch.jpeg
      author: llefevre
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Files excluded
exclude:
  - readme.md

# Build settings
# markdown: kramdown

# Jekyl plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
